#+Title: Golang
#+Date: <2018-09-15 Sat>
#+Author: Yogesh Agrawal
#+Email: yogeshiiith@gmail.com

* Introduction
  Here we will be learning golang.

* Setup
** Installation
   1. Downlod the package file from https://golang.org/dl/, open it
      and follow the prompts to install the Go tools. The package
      installs the Go distribution to =/usr/local/go=. And the package
      should put the =/usr/local/go/bin= directory in your PATH
      environment variable. You may need to restart any open terminal
      sessions for the change to take effect.
   2. Test installation:
      1. Create $HOME/go/src/hello directory.
      2. Create a hello.go
	 #+BEGIN_EXAMPLE
	package main

import "fmt"

func main() {
	fmt.Printf("hello, world\n")
}
	 #+END_EXAMPLE
      3. Do =cd $HOME/go/src/hello=
      4. go build
      5. ./hello
	 #+BEGIN_EXAMPLE
	 hello, world
	 #+END_EXAMPLE

** Uinstalling
   To remove an existing Go installation from your system delete the
   go directory. This is usually =/usr/local/go=. Also remove the
   =/etc/paths.d/go= file.

* Tour of Go
** Packages
   Every go program is made up of packages. Programs start running in
   package =main=. Following program is using the packages with
   imports paths "fmt" and "math/rand".
   #+BEGIN_SRC golang
   package main

   import (
      "fmt"
      "math/rand"
   )

   func main() {
       fmt.Println("My favorite number is", rand.Intn(10))
   }
   #+END_SRC

   By convention, the package name is the same as the last element of
   the import path. For instance, the =math/rand= package comprises
   files that begin with the statement =package rand=.

** imports
   Following code groups the imports into a parenthesized, "factored"
   import statement.
   #+BEGIN_SRC golang
   package main

   import (
       "fmt"
       "math"
   )

   func main(){
       fmt.Println("Now you have %g problems.", math.Sqrt(7))
   }
   #+END_SRC
   It is good style to use the factored import statement instead of
   using multiple import statements.
   #+BEGIN_SRC golang
   import "fmt"
   import "math"
   #+END_SRC

** Functions
   A function can take zero or more arguments. In the following
   example, add takes two parameters of type =int=.
   #+BEGIN_SRC golang
   package main

   import "fmt"

   func add(x int, y int) int {
       return x+y
   }

   func main(){
       fmt.Println(add(42, 13))
   }
   #+END_SRC
   Notice that the type comes after the variable name.

* Reference
  1. Golang installation: https://golang.org/doc/install
  2. Golang Tour https://tour.golang.org/welcome/1
  3. How to write go code: https://golang.org/doc/code.html
  4. Golang repository: https://github.com/golang/go
