#+Title: Golang
#+Date: <2018-09-15 Sat>
#+Author: Yogesh Agrawal
#+Email: yogeshiiith@gmail.com

* Introduction
  Here we will be learning golang.

* Setup
** Installation
   1. Downlod the package file from https://golang.org/dl/, open it
      and follow the prompts to install the Go tools. The package
      installs the Go distribution to =/usr/local/go=. And the package
      should put the =/usr/local/go/bin= directory in your =PATH=
      environment variable. You may need to restart any open terminal
      sessions for the change to take effect.

** Test installation
   - Create $HOME/go/src/hello directory.
   - Create a hello.go
     #+BEGIN_SRC go
package main

import "fmt"

func main() {
	fmt.Printf("hello, world\n")
}
     #+END_SRC
   - Do =cd $HOME/go/src/hello=
   - go build
   - ./hello
     #+BEGIN_EXAMPLE
     hello, world
     #+END_EXAMPLE

** Uinstalling
   To remove an existing Go installation from your system delete the
   go directory. This is usually =/usr/local/go=. Also remove the
   =/etc/paths.d/go= file.

* Tour of Go
** Basics
*** Packages, variables and functions
    Learn the basic components of any Go program.
**** Packages
     Every go program is made up of packages. Programs start running
     in package =main=. Following program is using the packages with
     imports paths "fmt" and "math/rand".
     #+BEGIN_SRC go
     package main

     import (
       	"fmt"
       	"math/rand"
     )

     func main() {
       	 fmt.Println("My favorite number is", rand.Intn(10))
     }
     #+END_SRC

     By convention, the package name is the same as the last element
     of the import path. For instance, the =math/rand= package
     comprises files that begin with the statement =package rand=.

**** imports
     Following code groups the imports into a parenthesized,
     "factored" import statement.
     #+BEGIN_SRC go
     package main

     import (
       	 "fmt"
       	 "math"
     )

     func main(){
       	 fmt.Printf("Now you have %g problems.\n", math.Sqrt(7))
     }
     #+END_SRC
     #+BEGIN_EXAMPLE
     Now you have 2.6457513110645907 problems.
     #+END_EXAMPLE

     It is good style to use the factored import statement instead of
     using multiple import statements.
     #+BEGIN_SRC go
     import "fmt"
     import "math"
     #+END_SRC

**** Exported Names
     In Go, a name is exported if it begins with a capital letter. For
     example, =Pizza= is an exported name, as is =Pi=, which is
     exported from the =math= package.

     When importing a package, you can refer only to its exported
     names. Any "unexported" names are not accessible from outside the
     package.

**** Functions
     A function can take zero or more arguments. In the following
     example, add takes two parameters of type =int=.
     #+BEGIN_SRC go
     package main

     import "fmt"

     func add(x int, y int) int {
       	 return x+y
     }

     func main(){
       	 fmt.Println(add(42, 13))
     }
     #+END_SRC
     Notice that the type comes after the variable name.

***** Multiple results
      A function can return any number of results. The =swap= function
      in the following example returns two strings.
      #+BEGIN_SRC go
package main

import "fmt"

func swap(x , y string) (string, string) {
  return y, x
}

func main() {
  a, b := swap("hello", "world")
  fmt.Println(a, b)
}
      #+END_SRC

***** Named return values
      Go's return values may be named. If so, they are treated as
      variables defined at the top of the function.

      These names should be used to document the meaning of the return
      values.

      A =return= statement without arguments returns the named return
      values. This is known as "naked" return.

      Naked returns should be used only in short functions, as with
      the following example. They can harm readability in longer
      functions.
    #+BEGIN_SRC go
package main

import "fmt"

func split(sum int) (x, y int) {
  x = sum * 4 / 9
  y = sum - x
  return
}

func main() {
  fmt.Println(split(17))
}
    #+END_SRC

**** Variables
     The =var= statement declares a list of variables; as in function
     arguments list, the type is last.

     A =var= statement can be at package or function level. We see
     both in the following example.
     #+BEGIN_SRC go
package main

import "fmt"

var c, python, java bool;

func main() {
  var i int;
  fmt.Println(i, c, python, java)
}

     #+END_SRC

***** Variables with initializers
      A var declaration can include initializers, one per variable.

      If an initializer is present, the type can be omitted; the
      variable will take the type of the initializer.
      #+BEGIN_SRC go
package main

import "fmt"

var c, python, java bool;
var d int = 2;
var e, f = 3, 4

func main() {
  var i int;
  fmt.Println(i, d, e, f, c, python, java)
}
      #+END_SRC

***** Short variable declarations
      Inside a function, the =:== short assignment statement can be
      used in place of a =var= declaration with implicit type.

      Outside a function, every statement begins with a keyword
      (=var=, =func=, and so on) and so the =:== construct is not
      available.
      #+BEGIN_SRC go
package main

import "fmt"

func main() {
  var i, j int = 1, 2
  k := 3
  c, python, java := true, false, "no!"

  fmt.Println(i, j, k, c, python, java)
}
      #+END_SRC

**** Types
     Go's basic types are
     #+BEGIN_EXAMPLE
     bool
     string
     int int8 int16 int32 int64
     byte // alias for uint8
     rune // alias for int32
         // represents a Unicode code point
     float32 float64
     complex64 complex128
     #+END_EXAMPLE

     Following example shows variables of several types, and also that
     variable declarations may be "factored" into blocks, as with
     import statements.
     #+BEGIN_SRC go
package main

import (
  "fmt"
  "math/cmplx"
  )

var (
  ToBe bool = false
  MaxInt uint64 = 1<<64 - 1
  z complex128 = cmplx.Sqrt(-5 + 12i)
)

func main() {
  fmt.Printf("Type: %T Value: %v\n", ToBe, ToBe)
  fmt.Printf("Type: %T Value: %v\n", MaxInt, MaxInt)
  fmt.Printf("Type: %T Value: %v\n", z, z)
}  
   #+END_SRC

     The =int, uint, uintptr= types are usually 32 bits wide on 32-bit
     systems and 64 bits wide on 64-bit systems. When you need an
     integer value you should use =int= unless you have a specific
     reason to use a signed or unsigned integer type.

***** Zero values
      Variables declared without an explicit initial value are given
      their zero value.

      The zero value is:
      #+BEGIN_EXAMPLE
      0 for numeric types
      false for the boolean type, and
      "" (the empty string) for strings.
      #+END_EXAMPLE
      Example:
      #+BEGIN_SRC go
package main

import "fmt"

func main() {
  var i int
  var f float64
  var b bool
  var s string
  fmt.Printf("%v %v %v %q\n", i, f, b, s)
}  
      #+END_SRC

***** Type conversions
      The expression =T(v)= converts the value =v= to the type =T=.
   
      Some numeric conversions:
      #+BEGIN_SRC go
      var i int = 42
      var f float64 = float64(i)
      var u uint = uint(f)
      #+END_SRC

      Or, put simply
      #+BEGIN_SRC go
    i := 42
    f := float64(i)
    u := uint(f)
    #+END_SRC
   
      Example:
      #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
  )

func main() {
  var x, y int = 3, 4
  var f float64 = math.Sqrt(float64(x * x + y * y))
  var z uint = uint(f)
  fmt.Println(x, y, z)
}
    #+END_SRC

      Unlike in C, in Go assignment between items of different types
      requires an explicit conversion. Try removing the =float64= or
      =uint= conversions in the example and see what happens.

***** Type inference
      When declaring a variable without specifying an explicit type
      (either by using the =:= syntax or =var == expression syntax),
      the variable's type is inferred from the value on the right hand
      side.

      When the right hand side of the declaration is typed, the new
      variable is of that same type:
      #+BEGIN_SRC go
      var i int
      j := i // j is an int
      #+END_SRC

      But when the right hand side contains an untyped numeric
      constant, the new variable may be an int, float64, or complex128
      depending on the precision of the constant:
      #+BEGIN_SRC go
      i := 42  // int
      f := 3.142 // float
      g := 0.867 + 0.5i // complex128
      #+END_SRC

      Example:
      #+BEGIN_SRC go
package main

import "fmt"

func main() {
  v := 42.3
  fmt.Printf("v is of type %T\n", v)
}
      #+END_SRC
      #+BEGIN_EXAMPLE
      v is of type float64
      #+END_EXAMPLE
    
      Try changing the initial value of =v= in the example code and
      observe how its type is affected.

***** Constants
      Constants are declared like variables, but with the =const= keyword.

      Constants can be character, string, boolean, or numeric values.
 
      Constants cannot be declared using the =:== syntax.

      Example:
      #+BEGIN_SRC go
package main

import "fmt"

const Pi = 3.14

func main() {
  const World = "world"
  fmt.Println("Hello", World)
  fmt.Println("Happy", Pi, "day")

  const Truth = true
  fmt.Println("Go rules?", Truth)

}
      #+END_SRC

*** Flow control statements: for, if, else, switch and defer
    Learn how to control the flow of your code with conditionals,
    loops, switches and defers.
**** For
     Go has only one looping structure, the =for= loop.

     The basic for loop has three components separated by semicolons:
    
     #+BEGIN_EXAMPLE
     the init statement: executed before the first iteration
     the condition statement: evaluated before every iteration
     the post statement: executed at the end of every iteration
     #+END_EXAMPLE

     The variables declared in the for loop are visible only in the
     scope of the =for= statement.
     #+BEGIN_SRC go
package main

import "fmt"

func main() {
  sum := 0
  for i := 0; i < 10; i++ {
    sum += i
  }

  fmt.Println(sum)

  for sum < 100 {
    sum += sum
  }

  fmt.Println(sum)

// infinite loop
  for {

  }

}   
    #+END_SRC
 
     There are no parentheses surrounding the three components of the
     =for= statement and the braces ={ }= are always required.

**** If
     Go's =if= statement are like =for= loops; the expression need not
     be surrounded by parentheses =()= but the braces ={}= are
     required.

     Like =for=, the =if= statement can start with a short statement
     to execute before the condition.

     Variables declared by the statement are only in scope until the
     end of the =if=.
     #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
)

func pow(x, n, lim float64) float64 {
  if v := math.Pow(x, n); v < lim {
    return v
  }
  return lim
}

func main() {
  fmt.Println(
    pow(3, 2, 10),
    pow(3, 3, 20),
  )
}    
     #+END_SRC

     Try using =v= in the last =return= statement.
     #+BEGIN_EXAMPLE
     # command-line-arguments
     src/hello/if.go:12:10: undefined: v
     #+END_EXAMPLE

**** If and else
     Variables declared inside an =if= short statement are also
     available inside any of the =else= blocks.

**** Switch
     A =switch= statement is a shorter way to write a sequence of
     =if - else= statements. It runs the first case whose value is
     equal to the condition expression.

     #+BEGIN_SRC go
package main

import (
  "fmt"
  "runtime"
)

func main() {
  fmt.Println("Go runs on")
  switch os := runtime.GOOS; os {
  case "darwin":
    fmt.Println("OS X.")
  case "linux":
    fmt.Println("Linux.")
  default:
    fmt.Printf("%s.", os)
  }
}
     #+END_SRC

**** Defer
     A defer statement defers the execution of a function until the
     surrounding funtion returns.

     The defered call's arguments are evaluated immediately, but the
     function call is not executed until the surrounding function
     returns.

     #+BEGIN_SRC go
package main

import "fmt"

func main() {
  defer fmt.Println("world")

  fmt.Println("hello")
}     
     #+END_SRC

*** More types: structs, slices, and maps
    Learn how to define types based on the existing ones: this lesson
    covers structs, arrays, slices and maps.
**** Pointers
     A points holds the memory address of a value.

     The type =*T= is a pointer to a =T= value. Its zero value is
     =nil=.

     =var p *int=

     The =&= operator generates a pointer to its operand.
     #+BEGIN_SRC go
     i := 42
     p = &i
     #+END_SRC
     
     The =*= operator denotes the pointer's underlying value.
     #+BEGIN_SRC go
     fmt.Println(*p)
     *p = 21
     #+END_SRC

     #+BEGIN_SRC go
package main

import "fmt"

func main() {
  i, j := 42, 2701

  p := &i
  fmt.Println(*p)

  *p = 21
  fmt.Println(i)

  p = &j
  *p = *p / 37
  fmt.Println(j)

  fmt.Println(p)

}     
     #+END_SRC

**** Structs
     A =struct= is a collection of fields.

     In the following example we are defining a type Vertex which is
     of type struct.
     #+BEGIN_SRC go
package main

import "fmt"

type Vertex struct {
  X int
  Y int
}

func main() {
  fmt.Println(Vertex{2, 3})
  fmt.Println(2)
}
     #+END_SRC

**** Pointers to structs
     Struct fields can be accessed through a struct pointer.

     To access the field =X= of a struct when we have the struct
     pointer =p= we could write =(*p).X=. However, that notation is
     cumbersome, so the language permits us instead to write just
     =p.X=, without the explicit dereference.
     #+BEGIN_SRC go
package main

import "fmt"

type Vertex struct {
  X int
  Y int
}

func main() {
  fmt.Println(Vertex{2, 3})
  fmt.Println(2)

  v := Vertex{1, 2}
  v.X = 4
  fmt.Println(v.X)

  p := &v
  p.X = 1e9
  fmt.Println(v)

}
     #+END_SRC
     #+BEGIN_EXAMPLE
{2 3}
2
4
{1000000000 2}
     #+END_EXAMPLE

     #+BEGIN_SRC go
package main

import "fmt"

type Vertex struct {
  X, Y int
}

var (
  v1 = Vertex{1, 2}
  v2 = Vertex{X: 1}
  v3 = Vertex{}
  p1 = &Vertex{1, 2}
  p2 = &v1
)

func main() {
  fmt.Println(v1, v2, v3, p1, &p2, *p1)
}
     #+END_SRC
     #+BEGIN_EXAMPLE
{1 2} {1 0} {0 0} &{1 2} 0x1133c90 {1 2}
     #+END_EXAMPLE
     
**** Arrays
     The type =[n]T= is an array of =n= values of type =T=.

     The expression
     #+BEGIN_SRC go
var a [10]int
     #+END_SRC
     declares a variable =a= as an array of ten integers.

     An array's length is part of its type, so arrays cannot be
     resized.
     #+BEGIN_SRC go
package main

import "fmt"

func main() {
  var a [2]string
  a[0] = "Hello"
  a[1] = "World"

  fmt.Println(a[0], a[1])
  fmt.Println(a)

  primes := [6]int{2, 3, 5, 7, 11, 13}
  fmt.Println(primes)

}
     #+END_SRC

**** Slices
     An array has a fixed size. A slice, on the other hand, is a
     dynamically-sized, flexible view into the elements of an
     array. In practise, slices are much more common than arrays.

     The type =[]T= is a slice with elements of type =T=.

     A slice is formed by specifying two indices, a low and high
     bound, separated by a colon.
     #+BEGIN_EXAMPLE
     a[low : high]
     #+END_EXAMPLE

     This selects a half-open range which includes the first element,
     but excludes the last one.
     #+BEGIN_SRC go
package main

import "fmt"

func main() {
  primes := [6]int{2, 3, 5, 7, 11, 13}

  var s []int = primes[1:4]
  fmt.Println(s)
}
     #+END_SRC

***** Pointers to slices
      Slices are like reference to arrays. A slice does not store any
      data, it just describes a section of an underlying array.

      Changing the elements of a slice modifies the corresponding
      elements of its underlying array.

      Other slices that share the same underlying array will see those
      changes.

      #+BEGIN_SRC go
package main

import "fmt"

func main() {
  names := [4]string{
    "John",
    "Paul",
    "George",
    "Ringo",
  }
  fmt.Println(names)

  a := names[0:2]
  b := names[1:3]
  fmt.Println(a, b)

  b[0] = "XXX"
  fmt.Println(a, b)
  fmt.Println(names)

}
     #+END_SRC

***** Slice literals
      #+BEGIN_SRC go
package main

import "fmt"

func main() {
  q := []int{2, 3, 5, 7, 11, 13}
  fmt.Println(q)

  r := []bool{true, false, true, true, false, true}
  fmt.Println(r)

  s := []struct{
    i int
    b bool
  }{
    {2, true},
    {3, false},
    {5, true},
    {7, true},
    {11, false},
    {13, true},
  }
  fmt.Println(s)
}
      #+END_SRC

***** Slice length and capacity
      The lenght of a slice is the number of elements it contains.

      The capacity of a slice is the number of elements in the
      underlying array, counting from the first element in the slice.

      The lenght and capacity of a slice =s= can be obtained using the
      expressions =len(s)= and =cap(s)=.

      #+BEGIN_SRC go
package main

import "fmt"

func main() {
  s := []int{2, 3, 5, 7, 11, 13}
  printSlice(s)

  // Slice the slice to give it zero length
  s = s[:0]
  printSlice(s)

  // Extend its length
  s = s[:4]
  printSlice(s)

  // Drop its first two element
  s = s[2:] // Note: capacity will become 4
  printSlice(s)

}

func printSlice(s []int){
  fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}
      #+END_SRC
      #+BEGIN_EXAMPLE
len=6 cap=6 [2 3 5 7 11 13]
len=0 cap=6 []
len=4 cap=6 [2 3 5 7]
len=2 cap=4 [5 7]
      #+END_EXAMPLE

***** Nil slices
      The zero value of a slice is =nil=.
      #+BEGIN_SRC go
package main

import "fmt"

func main() {
  var s []int
  fmt.Println(s, len(s), cap(s))
  if s == nil {
    fmt.Println("nil!")
  }
}     
      #+END_SRC

**** Range
     The =range= form of the =for= loop iterates over a slice or map.
     
     When ranging over a slice, two values are returned for each
     iteration. The first is index, and the second is a copy of the
     element at that index.
     #+BEGIN_SRC go
package main

import "fmt"

func main() {
  a := []int{1, 2, 4, 8, 16, 32}

  for i, v := range a {
    fmt.Printf("2**%d = %d\n", i, v)
  }

  // skip index by assigning to _.
  for _, v := range a {
    fmt.Println(v)
  }

}    
     #+END_SRC
     
**** Maps
     A map maps keys to values.

     The zero value of a map is =nil=. A =nil= map has no keys, nor
     can keys be added.

     The make function returns a map of the given type, initialized
     and ready for use.

     #+BEGIN_SRC go
package main

import "fmt"

type Vertex struct{
  Lat, Long float64
}

var m map[string]Vertex

func main() {
  m = make(map[string]Vertex)
  m["Bell labs"] = Vertex{
    40.68433, -74.39967,
  }
  fmt.Println(m["Bell labs"])
}
     #+END_SRC

**** Function values
     Functions are values too. They can be passed around just like
     other values.

     Function values may be used as function arguments and return
     values.

     #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
)

func compute(fn func(float64, float64) float64) float64{
  return fn(3, 4)
}

func main() {
  hypot := func(x, y float64) float64{
    return math.Sqrt(x*x + y*y)
  }

  fmt.Println(hypot(5, 12))

  fmt.Println(compute(hypot))
  fmt.Println(compute(math.Pow))
}     
     #+END_SRC

**** Function closures
     Go function may be closures. A closure is a function value that
     references variables from outiside its body. The function may
     access and assign to the referenced variables; in this sense the
     function is "bound" to the variables.
     
     In the following example, the adder function returns a
     closure. Each closure is bound to its own sum variable.

     #+BEGIN_SRC go
package main

import "fmt"

func adder() func (int) int {
  sum := 0
  return func(x int) int {
    sum += x
    return sum
  }
}

func main() {
  pos, neg := adder(), adder()
  for i := 0; i < 10; i++ {
    fmt.Println(
      pos(i),
      neg(-2 * i),
    )
  }
}    
     #+END_SRC

     Another example: Fibonacci closure:
     #+BEGIN_SRC go
package main

import "fmt"

func fibonacci() func() int {
  sec_last := -1
  last := 1
  return func() int {
    i := last
    last = sec_last + last
    sec_last = i
    return last
  }
}

func fibonacci2() func() int {
    first, second := 0, 1
    return func() int {
        ret := first
        first, second = second, first + second
        return ret
    }
}

func main() {
  f := fibonacci()
  for i := 0; i < 10; i++ {
    fmt.Println(f())
  }

  f2 := fibonacci2()
  for i := 0; i < 10; i++ {
    fmt.Println(f2())
  }

}
     #+END_SRC

** Methods and interfaces
*** Methods
    Go does not have classes. However, you can define methods on
    types. A method is a function with a special =receiver=
    argument. The receiver appears in its own argument list between
    the =func= keyword and the method name.

    In the following example, the =Abs= method has a receiver of type
    =Vertex= named =v=.

    #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
)

type Vertex struct {
  X, Y float64
}

func (v Vertex) Abs() float64 {
  return math.Sqrt(v.X*v.X + v.Y*v.Y)
}

func main() {
  v := Vertex{3, 4}
  fmt.Println(v.Abs())
}    
    #+END_SRC

    You can declare a method on non-struct types, too.

    #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
)

type MyFloat float64

func (f MyFloat) Abs() float64 {
  if f < 0 {
    return float64(-f)
  }
  return float64(f)
}

func main() {
  f := MyFloat(-math.Sqrt2)
  fmt.Println(f.Abs())
}   
    #+END_SRC

    You can only declare a method with a receiver whose type is
    defined in the same package as the method. You cannot declare a
    method with a receiver whose type is defined in another package
    (which includes the built-in types such as int).

*** Pointer receivers
    You can declare methods with pointer receivers.

    This means the receiver type has the literal syntax =*T= for some
    type =T=. (Also, T cannot itself be a pointer such as =*int=)

    For example, the =Scale= method here is defined on =*Vertex=.
    #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
)

type Vertex struct {
  X, Y float64
}

func (v Vertex) Abs() float64 {
  return math.Sqrt(v.X*v.X + v.Y*v.Y)
}

func (v *Vertex) Scale(f float64){
  v.X = v.X * f
  v.Y = v.Y * f
}

func main() {
  v := Vertex{3, 4}
  v.Scale(10)
  fmt.Println(v.Abs())
}    
    #+END_SRC

    Methods with pointer receivers can modify the value to which the
    receiver points (as =Scale= does here). Since methods often need
    to modify their receiver, pointer receivers are more common than
    value receivers.

*** Methods and pointers indirection
    Function with pointer argument must take a pointer. 
    #+BEGIN_SRC go
var v Vertex
ScaleFunc(v, 5) // comile error
ScaleFunc($v, 5) // OK
    #+END_SRC

    While methods with pointer receivers take either a value or a
    pointer as the receiver when they are called:
    #+BEGIN_SRC go
var v Vertex
v.Scale(5) // OK
p := &v
p.Scale(10) // OK
    #+END_SRC

    For the statement =v.Scale(5)=, even though =v= is a value and not
    a pointer, the method with the pointer receiver is called
    automatically. That is, as a convenience, Go interprets the
    statement =v.Scale(5)= as =(&v).Scale(5)= since the =Scale= method
    has a pointer receiver.
    
    #+BEGIN_SRC go
package main

import (
  "fmt"
  "reflect"
  )

type Vertex struct {
  X, Y float64
}

func (v *Vertex) Scale(f float64) {
  v.X = v.X * f
  v.Y = v.Y * f
}

func ScaleFunc(v *Vertex, f float64) {
  v.X = v.X * f
  v.Y = v.Y * f
}

func main() {
  v := Vertex{3, 4}
  v.Scale(2)
  ScaleFunc(&v, 10)

  p := &Vertex{4, 3}
  p.Scale(3)
  ScaleFunc(p, 8)

  fmt.Println(v, p)
  fmt.Println(reflect.TypeOf(v))
  fmt.Println(reflect.TypeOf(p))
}
    #+END_SRC

*** Interfaces
    An =interface= type is defined as a set of method signatures.

    A value of interface type can hold any value that implements those
    methods.

    #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
)

type Abser interface {
  Abs() float64
}

func main() {
  var a Abser
  v := Vertex{3, 4}
  f := Myfloat(-math.Sqrt2)

  a = f // a MyFloat implements Abser
  a = &v // a *Vertex implements Abser

  fmt.Println(a.Abs())
}

type Myfloat float64

func (f Myfloat) Abs() float64 {
  if f < 0 {
    return float64(-f)
  }
  return float64(f)
}

type Vertex struct {
  X, Y float64
}

func (v *Vertex) Abs() float64 {
  return math.Sqrt(v.X*v.X + v.Y*v.Y)
} 
    #+END_SRC

    Note: We cannot define new methods on non-local type. For example
    the following code will throw error
    #+BEGIN_SRC go
func (f float64) Abs() float64 {
  if f < 0 {
    return float64(-f)
  }
  return float64(f)
}   
    #+END_SRC
    #+BEGIN_EXAMPLE
    cannot define new methods on non-local type float64
    #+END_EXAMPLE

*** Interfaces are implemented implicitly
    A type implements an interface by implementing its methods. There
    is no explicit declaration of intent, no "implements" keyword.

    Implicit interfaces decouple the definition of an interface from
    its implementation, which could then appear in any package without
    prearrangement.

    #+BEGIN_SRC go
package main

import "fmt"

type I interface {
  M()
}

type T struct {
  S string
}

// This method means type T implements the interface I,
// but we don't need to explicitly declare that it does so.
func (t T) M() {
  fmt.Println(t.S)
}

func main() {
  var i I = T{"hello"}
  i.M()
}
    #+END_SRC

*** Interface values
    Under the hood, interface values can be though of as a tuple of a
    value and a concrete type:
    #+BEGIN_EXAMPLE
    (value, type)
    #+END_EXAMPLE

    An interface value holds a value of a specific underlying concrete
    type.

    Calling a method on an interface value executes the method of the
    same name on its underlying type.

    #+BEGIN_SRC go
package main

import (
  "fmt"
  "math"
)

type I interface {
  M()
}

func (t *T) M() {
  fmt.Println(t.S)
}

func (f F) M() {
  fmt.Println(f)
}

type T struct {
  S string
}

type F float64

func main(){
  var i I

  i = &T{"Hello"}
  describe(i)
  i.M()

  i = F(math.Pi)
  describe(i)
  i.M()

}

func describe(i I){
  fmt.Printf("(%v, %T)\n", i, i)
}
    #+END_SRC

* Reference
  1. Golang installation: https://golang.org/doc/install
  2. Golang Tour https://tour.golang.org/welcome/1
  3. How to write go code: https://golang.org/doc/code.html
  4. Golang repository: https://github.com/golang/go
